branches:
  only:
    - master
    

language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-frontend:latest ./Testother
  - docker tag udagram-frontend:latest mostafaibrahim/udagram-frontend:v22


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mostafaibrahim/udagram-frontend:v22
